### ISSUE TITLE
Usage of `rai.NopAccessTokenHandler{}` leads to crash

### ISSUE THREAD

**Issue by Segflow** [RelationalAI/rai-sdk-go#3]
As I love working with Go, I'm using the SDK to do some local development (hit a local transaction service). 

To bypass auth I'm using `rai.NopAccessTokenHandler{}`

```
	client, err := rai.NewClientFromConfig(opts.Profile)
	if err != nil {
		return err
	}

	client.SetAccessTokenHandler(rai.NopAccessTokenHandler{})
```

But this lead to crashes because of this code: https://github.com/RelationalAI/rai-sdk-go/blob/main/rai/client.go#L178-L185

Crash: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1266149]

goroutine 1 [running]:
net/http.(*Request).WithContext(...)
        /usr/local/Cellar/go/1.18.1/libexec/src/net/http/request.go:360
github.com/relationalai/rai-sdk-go/rai.(*Client).Do(0xc00015c100?, 0x0?)
        /Users/segflow/work/rai-sdk-go/rai/client.go:342 +0x89
github.com/relationalai/rai-sdk-go/rai.(*Client).request(0x1?, {0x12d9670, 0x4}, {0x12db609, 0xc}, 0xc00012fb19?, {0x12966e0, 0xc000109290}, {0x12921e0, 0xc000074240})
        /Users/segflow/work/rai-sdk-go/rai/client.go:295 +0x148
github.com/relationalai/rai-sdk-go/rai.(*Client).Post(...)
        /Users/segflow/work/rai-sdk-go/rai/client.go:225
github.com/relationalai/rai-sdk-go/rai.(*Client).Execute(0xc00015c100, {0x7ff7bfeff9aa, 0x7}, {0x7ff7bfeff9b5, 0xb}, {0xc000024180, 0x5c}, 0x10199e0?, 0x0)
        /Users/segflow/work/rai-sdk-go/rai/client.go:964 +0x1a6
github.com/relationalai/rai-sdk-go/rai.(*Client).LoadCSV(0xd?, {0x7ff7bfeff9aa, 0x7}, {0x7ff7bfeff9b5, 0xb}, {0x7ff7bfeff9c7, 0x6}, {0x1356e00?, 0xc000010080?}, 0xc00012ff00)
        /Users/segflow/work/rai-sdk-go/rai/client.go:1116 +0x1b8
main.run(0xc0000121b0)
        /Users/segflow/work/rai-sdk-go/examples/load_csv/main.go:71 +0x265
main.main()
        /Users/segflow/work/rai-sdk-go/examples/load_csv/main.go:84 +0x65
exit status 2
```

Since `NopAccessTokenHandler` is returning an empty token line 181 is returning a `nil` request and an empty token. 

Later here https://github.com/RelationalAI/rai-sdk-go/blob/main/rai/client.go#L289-L293

we override the req with the returned result and since it's `nil` a crash will happen later on.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5185](https://relationalai.atlassian.net/browse/RAI-5185).

_This link is only accessible to employees of RelationalAI._
